jobs:
  build_deploy:
    machine:
      image:ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
        name: Installling AWS CLI
        command: |
          sudo apt-get update
          sudo apt install python3-pip
          sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - run: aws s3 sync ./app/build s3://cicdelvisgpt

workflows:
    version: 1
    execute_bulk:
      jobs:
        - build_deploy
        
